### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by AvnyrTokirawa** [H1DD3NxN1NJA/ChatManager#1]
[13:48:02] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ChatManager v3.1.0

org.bukkit.event.EventException: null

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Caused by: java.lang.NullPointerException

	at me.H1DD3NxN1NJA.ChatManager.Listeners.ListenerPlayerJoin.onPlayerJoin(ListenerPlayerJoin.java:88) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]

	... 14 more

**Comment by H1DD3NxN1NJA** [comment]
Can you send me your config in pastbin or hastbin?

**Comment by AvnyrTokirawa** [comment]
LinkLife : 1week

https://pastebin.com/yS0Yxh14

**Comment by H1DD3NxN1NJA** [comment]
Ok, I found the problem, change the join and quit message in the config from this...

  Join: "&2{player} &aest là !"
 
  Quit: "&2{player} &aest parti."

to this...

  Join_Message: "&2{player} &aest là !"
 
  Quit_Message: "&2{player} &aest parti."

If you have any other problems please let me know.
