### ISSUE TITLE
java.lang.NullPointerException [PlayerJoinEvent/PlayerQuitEvent] (Again)

### ISSUE THREAD

**Issue by AvnyrTokirawa** [H1DD3NxN1NJA/ChatManager#2]
Could not pass event **PlayerQuitEvent** to ChatManager v3.1.0

```

> org.bukkit.event.EventException: null
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:405) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1104) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:321) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

Caused by: **java.lang.NullPointerException**

-------------------------------------------------------------

Could not pass event **PlayerJoinEvent** to ChatManager v3.1.0

```
> org.bukkit.event.EventException: null
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

Caused by: **java.lang.NullPointerException**

> Plugin ChatManager v3.1.0 generated an exception while executing task 1866259
java.lang.NullPointerException: null

[**Config.yml**](https://pastebin.com/51DvBFce)
_Link life: 2weeks_

**Server type**
_Fr_
_Survival/Medieval/Rp_
> Spigot 1.12.2
> Plugin : 41

**Comment by H1DD3NxN1NJA** [comment]
I don't see anything wrong with your config, I'm going to post an update to fix a small typo in my code with first join title messages to see if that fixes it.

**Comment by AvnyrTokirawa** [comment]
Okay god luck ^^
