### ISSUE TITLE
Could not pass event PlayerJoinEvent to ChatManager v3.7.6

### ISSUE THREAD

**Issue by ghost** [H1DD3NxN1NJA/ChatManager#29]
[12:48:08 ERROR]: Could not pass event PlayerJoinEvent to ChatManager v3.7.6
java.lang.NullPointerException: Cannot invoke "net.milkbowl.vault.chat.Chat.getPlayerPrefix(org.bukkit.entity.Player)" because "me.h1dd3nxn1nja.chatmanager.hooks.VaultHook.chat" is null
        at me.h1dd3nxn1nja.chatmanager.hooks.VaultHook.getPlayerPrefix(VaultHook.java:26) ~[?:?]
        at me.h1dd3nxn1nja.chatmanager.managers.PlaceholderManager.setPlaceholders(PlaceholderManager.java:35) ~[?:?]
        at me.h1dd3nxn1nja.chatmanager.listeners.ListenerPlayerJoin.onJoinTitle(ListenerPlayerJoin.java:146) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor133.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-12]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-12]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-12]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:173) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1587) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1407) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-12]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by xSoranox** [comment]
I solved this problem by downloading LuckPerms plugin to the server. You should have both Vault and LuckPerms plugins
