### ISSUE TITLE
[20:58:02 WARN]: [ChatManager] Task #110 for ChatManager v3.7.7 generated an exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Joey1222** [H1DD3NxN1NJA/ChatManager#36]
[20:58:02 WARN]: [ChatManager] Task #110 for ChatManager v3.7.7 generated an exception
java.lang.NullPointerException: null

**Comment by Joey1222** [comment]
Its Keep Happening!

**Comment by Joey1222** [comment]
#110 and #111

**Comment by EncryptEx** [comment]
Same. In our case its task #104

**Comment by EncryptEx** [comment]
I'll attach the entire error in my case: 
```
Server thread/WARN]: [ChatManager] Task #104 for ChatManager v3.7.7 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.util.regex.Matcher.getTextLength(Matcher.java:1769) ~[?:?]
        at java.util.regex.Matcher.reset(Matcher.java:415) ~[?:?]
        at java.util.regex.Matcher.<init>(Matcher.java:252) ~[?:?]
        at java.util.regex.Pattern.matcher(Pattern.java:1134) ~[?:?]
        at me.h1dd3nxn1nja.chatmanager.Methods.color(Methods.java:68) ~[?:?]
        at me.h1dd3nxn1nja.chatmanager.managers.AutoBroadcastManager$1.run(AutoBroadcastManager.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[server.jar:3284a-Spigot-3892929-0ab8487]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```
