### ISSUE TITLE
CRAZY CONSOLE ERROR

### ISSUE THREAD

**Issue by successed** [H1DD3NxN1NJA/ChatManager#5]
[13:14:00 WARN]: [ChatManager] Task #3844 for ChatManager v3.5.2 generated an exception
java.lang.NullPointerException: null
        at me.h1dd3nxn1nja.chatmanager.listeners.ListenerCooldowns$1.run(ListenerCooldowns.java:42) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-156]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-156]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-156]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by xCykrix** [comment]
Please make sure you either update configurations or regenerate. Latest version has deprecated old configs. 
SpigotMC has the updates in release history.

_Sent from my Moto Z (2) Play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
